# Cloud Build Configuration for LEGID Backend
# Builds and deploys the backend service to Cloud Run

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/legid-backend:latest'
      - '-t'
      - 'gcr.io/$PROJECT_ID/legid-backend:$SHORT_SHA'
      - '-f'
      - 'backend/Dockerfile'
      - 'backend'
    id: 'build-backend-image'

  # Step 2: Push the Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/legid-backend:latest'
    id: 'push-backend-image'
    waitFor: ['build-backend-image']

  # Step 3: Push the tagged image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/legid-backend:$SHORT_SHA'
    id: 'push-backend-tagged-image'
    waitFor: ['build-backend-image']

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'legid-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/legid-backend:latest'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      - '--set-secrets'
      - 'OPENAI_API_KEY=OPENAI_API_KEY:latest,JWT_SECRET_KEY=JWT_SECRET_KEY:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,MICROSOFT_CLIENT_ID=MICROSOFT_CLIENT_ID:latest,MICROSOFT_CLIENT_SECRET=MICROSOFT_CLIENT_SECRET:latest'
      - '--set-env-vars'
      - 'LLM_PROVIDER=openai,ENVIRONMENT=production,LOG_LEVEL=INFO,PORT=8000'
    id: 'deploy-to-cloud-run'
    waitFor: ['push-backend-image']

# Images to be pushed to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/legid-backend:latest'
  - 'gcr.io/$PROJECT_ID/legid-backend:$SHORT_SHA'

# Substitutions for customization
substitutions:
  _REGION: 'us-central1'

# Build options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  
# Timeout
timeout: '1800s'
