# Cloud Build configuration for Legal AI Application
# Deploys both backend and frontend to Cloud Run

substitutions:
  _REGION: us-central1
  _BACKEND_SERVICE: legal-bot-backend
  _FRONTEND_SERVICE: legal-bot-frontend
  _BACKEND_MEMORY: 4Gi
  _BACKEND_CPU: '2'
  _FRONTEND_MEMORY: 512Mi
  _FRONTEND_CPU: '1'

steps:
  # ============================================
  # BACKEND BUILD AND DEPLOY
  # ============================================
  
  # Step 1: Build Backend Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:latest'
      - '-f'
      - 'backend/Dockerfile'
      - 'backend'
    timeout: '1200s'
  
  # Step 2: Push Backend Image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}'
    waitFor: ['build-backend']
  
  # Step 3: Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy ${_BACKEND_SERVICE} \
          --image=gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$SHORT_SHA \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --memory=${_BACKEND_MEMORY} \
          --cpu=${_BACKEND_CPU} \
          --timeout=300 \
          --concurrency=80 \
          --min-instances=0 \
          --max-instances=10 \
          --port=8000 \
          --set-env-vars="GOOGLE_CLOUD_PROJECT=$PROJECT_ID" \
          --set-secrets="OPENAI_API_KEY=OPENAI_API_KEY:latest,GOOGLE_CLIENT_ID=GOOGLE_CLIENT_ID:latest,GOOGLE_CLIENT_SECRET=GOOGLE_CLIENT_SECRET:latest,JWT_SECRET_KEY=JWT_SECRET_KEY:latest" \
          --update-secrets="MICROSOFT_CLIENT_ID=MICROSOFT_CLIENT_ID:latest,MICROSOFT_CLIENT_SECRET=MICROSOFT_CLIENT_SECRET:latest" || \
        gcloud run deploy ${_BACKEND_SERVICE} \
          --image=gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$SHORT_SHA \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --memory=${_BACKEND_MEMORY} \
          --cpu=${_BACKEND_CPU} \
          --timeout=300 \
          --concurrency=80 \
          --min-instances=0 \
          --max-instances=10 \
          --port=8000 \
          --set-env-vars="GOOGLE_CLOUD_PROJECT=$PROJECT_ID" \
          --set-secrets="OPENAI_API_KEY=OPENAI_API_KEY:latest"
    waitFor: ['push-backend']

  # Step 4: Get Backend URL for Frontend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'get-backend-url'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BACKEND_URL=$(gcloud run services describe ${_BACKEND_SERVICE} --region=${_REGION} --format='value(status.url)')
        echo $BACKEND_URL > /workspace/backend_url.txt
        echo "Backend URL: $BACKEND_URL"
    waitFor: ['deploy-backend']

  # ============================================
  # FRONTEND BUILD AND DEPLOY
  # ============================================
  
  # Step 5: Build Frontend Docker Image (with Backend URL)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    entrypoint: 'bash'
    args: 
      - '-c'
      - |
        BACKEND_URL=$(cat /workspace/backend_url.txt)
        docker build \
          --build-arg VITE_API_URL=$BACKEND_URL \
          -t gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:$SHORT_SHA \
          -t gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:latest \
          -f frontend/Dockerfile \
          frontend
    waitFor: ['get-backend-url']
    timeout: '600s'

  # Step 6: Push Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    args:
      - 'push'
      - '--all-tags'
      - 'gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}'
    waitFor: ['build-frontend']
  
  # Step 7: Deploy Frontend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BACKEND_URL=$(cat /workspace/backend_url.txt)
        gcloud run deploy ${_FRONTEND_SERVICE} \
          --image=gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:$SHORT_SHA \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --memory=${_FRONTEND_MEMORY} \
          --cpu=${_FRONTEND_CPU} \
          --timeout=300 \
          --min-instances=0 \
          --max-instances=10 \
          --port=80 \
          --set-env-vars="API_URL=$BACKEND_URL"
    waitFor: ['push-frontend']

  # Step 8: Output deployment URLs
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'output-urls'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "============================================"
        echo "DEPLOYMENT COMPLETE!"
        echo "============================================"
        echo ""
        BACKEND_URL=$(gcloud run services describe ${_BACKEND_SERVICE} --region=${_REGION} --format='value(status.url)')
        FRONTEND_URL=$(gcloud run services describe ${_FRONTEND_SERVICE} --region=${_REGION} --format='value(status.url)')
        echo "Backend API:  $BACKEND_URL"
        echo "Frontend App: $FRONTEND_URL"
        echo ""
        echo "Health Check: $BACKEND_URL/health"
        echo "API Docs:     $BACKEND_URL/docs"
        echo "============================================"
    waitFor: ['deploy-frontend']

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'

timeout: '2400s'

images:
  - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:latest'
  - 'gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:latest'
